### ISSUE TITLE
Editor - UI

### ISSUE THREAD

**Issue by yeasirh** [eungella-io/Killara#16]

**Comment by yeasirh** [comment]
@dipankar-chaki

**Comment by dipankar-chaki** [comment]
`yarn add  @mantine/rte`

**Comment by dipankar-chaki** [comment]
`yarn add @mantine/styles`

**Comment by dipankar-chaki** [comment]
Need to check this, seems to be working when we add these two libs

`yarn add @emotion/react @emotion/styled`
