### ISSUE TITLE
App Icons - UI

### ISSUE THREAD

**Issue by lifeparticle** [eungella-io/Killara#20]

**Comment by lifeparticle** [comment]
https://iconoir.com/

**Comment by yeasirh** [comment]
Create folder:  https://iconoir.com/source/add-folder.svg

Folder: https://iconoir.com/source/folder.svg

File:  https://iconoir.com/source/page.svg

Create file: https://iconoir.com/source/add-page.svg

Save: https://iconoir.com/source/save-floppy-disk.svg

Delete: https://iconoir.com/source/trash.svg

Play wizard: 
- https://iconoir.com/source/arcade.svg
- https://iconoir.com/source/hexagon-dice.svg
- https://iconoir.com/source/playstation-gamepad.svg

**Comment by lifeparticle** [comment]
The [hexagon-dice.svg](https://iconoir.com/source/hexagon-dice.svg) looks nice!

**Comment by lifeparticle** [comment]
https://github.com/eungella-io/Killara/discussions/32
